name: deepfake
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.5.0
  - torchvision=0.20.0
  - pytorch-cuda=11.8
  - numpy=1.26.4
  - pandas=2.2.0
  - pillow=10.2.0
  - pyyaml=6.0.1
  - tqdm=4.66.2
  - pip
  - pip:
    - timm==1.0.3
    - opencv-python==4.9.0.80
    - ultralytics==8.1.0
    - supervision==0.19.0
    - huggingface-hub==0.21.0
    - transformers==4.38.0
